inf = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(inf))
print('Só tem espaço?', inf.isspace())
print('É um número?', inf.isnumeric())
print('É alfabético?', inf.isalpha())
print('É alfanumérico?', inf.isalnum())
print('Está em maiúsculaS?', inf.isupper())
print('Está emm minúsculas?', inf.islower())
print('Está capitalizada?', inf.istitle())
